
name: deploy-ui
on:
  push:
    branches: [ "main" ]
    paths:
      - 'ui/**'
      - 'Dockerfile.ui'
      - '.github/workflows/deploy-ui.yml'
      - 'requirements.txt'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: ACR login
        run: az acr login -n ${{ secrets.ACR_NAME }}
      - name: Build & push
        run: |
          ACR=${{ secrets.ACR_LOGIN_SERVER }}
          IMAGE=$ACR/ui:${{ github.sha }}
          docker build -t $IMAGE -f Dockerfile.ui .
          docker push $IMAGE
      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy@v1
        with:
          containerAppName: ts-ui
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/ui:${{ github.sha }}
          environmentVariables: |
            API_BASE=https://REPLACE_API_FQDN
