name: Build UI Image
on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
      - 'Dockerfile.ui'
      - 'requirements-ui.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ui
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tenderbot-ui:latest
